# Site settings
title: SturdyEgg
header-img: img/home-bg.jpg
email: sturdyegg@gmail.com
description: "Project align"
baseurl: /step
url: "https://deplax.github.com/step"
github_username: deplax
mini-title: SturdyEgg



# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
